### ISSUE TITLE
Travis CI build times out

### ISSUE THREAD

**Issue by arkottke** [abrahamson/HAZ#30]
Travis CI stops the build because no output has been received for 10 minutes:

> Running HAZ on: ../tests/Set3/S3Test3/Approach a/Run_S3Test3.txt
> At line 526 of file /home/travis/build/arkottke/HAZ/HAZ files/readFlt.f (unit = 10, file = 'Source_S3Test3.txt')
> Fortran runtime error: End of file
> Running HAZ on: ../tests/Set3/S3Test3/Approach b1/Run_S3Test3.txt
> Running HAZ on: ../tests/Set3/S3Test1a/Run_S3Test1a.txt
> Running HAZ on: ../tests/Set3/S3Test1b/Run_S3Test1b.txt
> Running HAZ on: ../tests/Set3/S3Test2/Fractiles/Run_Fractiles.txt
> STOP 99
> Running HAZ on: ../tests/Set3/S3Test2/Hazard/Run_S3Test2.txt
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

**Comment by ChristieHale** [comment]
Commits 34500ac and ffeef82 are addressing issues with Set 3 tests.
